name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        TAG=$(date -u +%Y%m%d%H%M%S)
        echo ${{secrets.MASE_DOCKER_CRED}} | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
        docker build --build-arg VHLS_PATH=/mnt/applications/Xilinx/23.1 \
        --build-arg VHLS_VERSION=2023.1 \
        -f Dockerfile \
        --tag ghcr.io/${{github.repository}}/mase-ci-build:$TAG . || exit 1

        # Push to ghcr
        docker push ghcr.io/${{github.repository}}/mase-ci-build:$TAG
        docker tag ghcr.io/${{github.repository}}/mase-ci-build:$TAG ghcr.io/${{github.repository}}/mase-ci-build:latest
        docker push ghcr.io/${{github.repository}}/mase-ci-build:latest

        # Push to dockerhub
        echo ${{secrets.DOCKER_HUB_PASSWORD}} | docker login docker.io -u deepwok --password-stdin
        docker push docker.io/deepwok/mase-docker:$TAG
        docker tag docker.io/deepwok/mase-docker:$TAG docker.io/deepwok/mase-docker:latest
        docker push docker.io/deepwok/mase-docker:latest
